name: CI

on:
  push:

jobs:
  build-executable:
    name: Build executale
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - uses: 40ants/setup-lisp@v1
        with:
          asdf-system: portofino-cli
      - name: Build executable
        run: |
          PATH="~/.roswell/bin:$PATH"
          qlot exec build-executable.ros