name: Build Linux executable

on:
  push:

jobs:
  build-executable:
    name: Build executale
    runs-on: ubuntu-latest
    env:
      LISP: sbcl
    steps:
      - uses: actions/checkout@v3
      # Caching - see https://github.com/40ants/setup-lisp
      - name: Grant All Perms to Make Cache Restoring Possible
        run: |
          sudo mkdir -p /usr/local/etc/roswell
          sudo chown "${USER}" /usr/local/etc/roswell
          # Here the ros binary will be restored:
          sudo chown "${USER}" /usr/local/bin
      - name: Get Current Month
        id: current-month
        run: |
          echo "::set-output name=value::$(date -u "+%Y-%m")"
      - name: Cache Roswell Setup
        id: cache
        uses: actions/cache@v3
        env:
          cache-name: cache-roswell
        with:
          path: |
            /usr/local/bin/ros
            ~/.cache/common-lisp/
            ~/.roswell
            /usr/local/etc/roswell
            .qlot
          key: "${{ steps.current-month.outputs.value }}-${{ env.cache-name }}-${{ runner.os }}-${{ hashFiles('qlfile.lock') }}"
      - name: Restore Path To Cached Files
        run: |
          echo $HOME/.roswell/bin >> $GITHUB_PATH
          echo .qlot/bin >> $GITHUB_PATH
        if: steps.cache.outputs.cache-hit == 'true'
      - uses: 40ants/setup-lisp@v2
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          asdf-system: portofino-cli
          qlfile-template: |
            dist ultralisp http://dist.ultralisp.org
      - name: Prepare system
        run: |
          sudo apt-get update -qq;
          sudo apt-get install -y rubygems sbcl;
          sudo gem install --no-document fpm;
          git clone --depth=1 --branch=sbcl-2.0.10 https://github.com/sbcl/sbcl.git ~/sbcl &> /dev/null;
      - name: Build executable
        run: |
          ros use sbcl/system;
          PATH=~/.roswell/bin:$PATH
          ros run -- --eval "(progn (asdf:load-asd \"`pwd`/portofino-cli.asd\") (ql:quickload :portofino-cli) (asdf:make :portofino-cli/executable) (quit))"
	  chmod +x ./portofino
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: portofino-linux
          path: portofino