name: Build OSX Application

on:
  push:

jobs:
  build-executable:
    name: Build executale
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 40ants/setup-lisp@v1
        with:
          asdf-system: portofino-cli
      - name: Build executable
        run: |
          PATH="~/.roswell/bin:$PATH"
          ros run -- --eval "(progn (asdf:load-asd \"`pwd`/portofino-cli.asd\") (ql:quickload :deploy) (asdf:load-asd \"`pwd`/portofino-cli-osx-app.asd\") (asdf:make :portofino-cli-osx-app) (ql:quickload :portofino-cli/executable))"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: portofino-osx
          path: bin