name: Build Debian package

on:
  push:

jobs:
  build-executable:
    name: Build executale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 40ants/setup-lisp@v1
        with:
          asdf-system: portofino-cli
      - name: Build executable
        run: |
          PATH="~/.roswell/bin:$PATH"
          ros run -- --eval "(progn (asdf:load-asd \"`pwd`/portofino-cli.asd\") (ql:quickload :linux-packaging) (asdf:load-asd \"`pwd`/portofino-cli-deb.asd\") (asdf:make :portofino-cli/deb))"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: portofino.deb
          path: portofino.deb