name: Build Debian package

on:
  push:

jobs:
  build-executable:
    name: Build executale
    runs-on: ubuntu-latest
    env:
      LISP: sbcl
    steps:
      - uses: actions/checkout@v1
      - uses: 40ants/setup-lisp@v1
        with:
          asdf-system: portofino-cli
      - name: Prepare system
        run: |
          sudo apt-get update -qq;
          sudo apt-get install -y ruby ruby-dev rubygems dpkg-dev sbcl curl git-core zlib1g-dev;
          gem install --no-document fpm &> /dev/null;
      - name: Build executable
        run: |
          PATH=~/.gem/ruby/$(ls ~/.gem/ruby)/bin:~/.roswell/bin:$PATH
          ros run -- --eval "(progn (asdf:load-asd \"`pwd`/portofino-cli.asd\") (ql:quickload :linux-packaging) (asdf:load-asd \"`pwd`/portofino-cli-deb.asd\") (asdf:make :portofino-cli-deb))"
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: portofino.deb
          path: portofino.deb