name: CI (Windows)

on:
  push:

jobs:
  build-executable:
    name: Build executale
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1
      - uses: 40ants/setup-lisp@v1
        with:
          asdf-system: portofino-cli
      - name: Build executable
        shell: bash
        run: |
          PATH="~/.roswell/bin:/c/roswell/bin:$PATH"
          qlot exec ${{ github.action_path }}/build-executable.ros