name: CI (Windows)

on:
  push:

jobs:
  build-executable:
    name: Build executale
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Install Roswell
        env:
          LISP: sbcl-bin
          ROSWELL_INSTALL_DIR: /c/roswell
        shell: bash
        run: |
          PATH="/c/roswell/bin:$PATH"
          curl -L https://raw.githubusercontent.com/fukamachi/roswell/windows-source-registry-settings/scripts/install-for-ci.sh | sh
      - name: Build executable
        shell: bash
        run: |
          PATH="~/.roswell/bin:/c/roswell/bin:$PATH"
          ros run -- --eval "(progn (asdf:load-asd \"`pwd`/portofino-cli.asd\") (ql:quickload :portofino-cli/executable))"
      - name: Rename executable
        shell: bash
        run: mv portofino portofino.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: portofino-cli-windows
          path: portofino.exe